version: '3.7'
services:
  app:
    image: sibisam2301/maven:${TAG_NUMBER}
    ports:
      - "7079:7079"  # Mapping port 8080 of the container to port 8080 on the host
    environment:
      - ENV_VAR=production
    volumes:
      - ./app:/app

